package org.example.model

/**
 * Enum класс, который описывает время, на которое можно отложить уведомление
 *
 * NOTIFICATION_SNOOZE_UNSPECIFIED - время не указано NOTIFICATION_SNOOZE_5_MINUTES - 5 минут
 * NOTIFICATION_SNOOZE_15_MINUTES - 15 минут NOTIFICATION_SNOOZE_30_MINUTES - 30 минут
 * NOTIFICATION_SNOOZE_1_HOUR - 1 час NOTIFICATION_SNOOZE_5_HOURS - 5 часов
 * NOTIFICATION_SNOOZE_1_DAY - 1 день
 */
enum class NotificationSnoozeEnum {
  NOTIFICATION_SNOOZE_UNSPECIFIED,
  NOTIFICATION_SNOOZE_5_MINUTES,
  NOTIFICATION_SNOOZE_15_MINUTES,
  NOTIFICATION_SNOOZE_30_MINUTES,
  NOTIFICATION_SNOOZE_1_HOUR,
  NOTIFICATION_SNOOZE_5_HOURS,
  NOTIFICATION_SNOOZE_1_DAY
}
