package org.example.model

enum class NotificationSnoozeEnum {
  NOTIFICATION_SNOOZE_UNSPECIFIED,
  NOTIFICATION_SNOOZE_5_MINUTES,
  NOTIFICATION_SNOOZE_15_MINUTES,
  NOTIFICATION_SNOOZE_30_MINUTES,
  NOTIFICATION_SNOOZE_1_HOUR,
  NOTIFICATION_SNOOZE_5_HOURS,
  NOTIFICATION_SNOOZE_1_DAY
}